In [4]:
import numpy as np
import numpy.linalg as lin

## Load Dataset

In [19]:
x = np.random.uniform(low=0.0, high=1.0, size=100)

print(x.shape)
x[:10]

(100,)


array([ 0.2166276 ,  0.51159707,  0.96526662,  0.53512056,  0.56391138,
        0.53412788,  0.11336495,  0.61263031,  0.93458419,  0.27741529])

In [20]:
y = x * 0.3

print(y.shape)
y[:10]

(100,)


array([ 0.06498828,  0.15347912,  0.28957999,  0.16053617,  0.16917341,
        0.16023836,  0.03400948,  0.18378909,  0.28037526,  0.08322459])

In [21]:
x1 = np.random.uniform(low=0.0, high=1.0, size=100)

print(x1.shape)
x1[:10]

(100,)


array([ 0.66664485,  0.36150915,  0.75891455,  0.2056365 ,  0.8453952 ,
        0.06547229,  0.95392189,  0.7490997 ,  0.5947914 ,  0.76300265])

In [22]:
x2 = np.random.uniform(low=0.0, high=1.0, size=100)

print(x2.shape)
x2[:10]

(100,)


array([ 0.86370694,  0.58403047,  0.48736614,  0.04944416,  0.07796703,
        0.12418902,  0.74907461,  0.57801307,  0.28542497,  0.25224235])

In [23]:
y1 = x1 * 0.3 + x2 * 0.5 + 0.1

print(y.shape)
y[:10]

(100,)


array([ 0.06498828,  0.15347912,  0.28957999,  0.16053617,  0.16917341,
        0.16023836,  0.03400948,  0.18378909,  0.28037526,  0.08322459])

### Case 1 - Random Search

In [24]:
num_epoch = 100000

best_epoch = None
best_w = None
best_error = np.inf

for epoch in range(num_epoch):
    w1 = np.random.uniform(low=0.0, high=1.0)
    w2 = np.random.uniform(low=0.0, high=1.0)
    b = np.random.uniform(low=0.0, high=1.0)
    
    y_predict = w1 * x1 + w2 * x2 + b
    
    error = np.abs(y1 - y_predict).mean()
    
    if error < best_error:
        best_error = error
        best_w1 = w1
        best_w2 = w2
        best_b = b
        best_epoch = epoch
    
        print("{0} error = {1:.5f}, w1 = {2:.5f}, w2 = {3:.5f}, b = {4:.5f}"\
              .format(best_epoch, best_error, best_w1, best_w2, best_b))
        
print("------" * 10)
print("{0} error = {1:.5f}, w1 = {2:.5f}, w2 = {3:.5f}, b = {4:.5f}"\
      .format(best_epoch, best_error, best_w1, best_w2, best_b))

0 error = 0.39844, w1 = 0.41652, w2 = 0.38680, b = 0.49258
1 error = 0.21011, w1 = 0.00445, w2 = 0.97771, b = 0.21905
3 error = 0.12679, w1 = 0.25841, w2 = 0.79166, b = 0.10951
11 error = 0.02730, w1 = 0.31162, w2 = 0.58032, b = 0.07968
1471 error = 0.01275, w1 = 0.33978, w2 = 0.50741, b = 0.08760
1709 error = 0.01247, w1 = 0.25150, w2 = 0.47949, b = 0.12862
10732 error = 0.00963, w1 = 0.27315, w2 = 0.51674, b = 0.11383
32046 error = 0.00456, w1 = 0.30201, w2 = 0.51536, b = 0.09470
------------------------------------------------------------
32046 error = 0.00456, w1 = 0.30201, w2 = 0.51536, b = 0.09470


### Case 2 - H-Step Search

In [25]:
num_epoch = 100000
h = 0.001

w = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_predict = w * x
    current_error = np.abs(y - y_predict).mean()
    
    y_predict = (w + h) * x
    h_plus_error = np.abs(y - y_predict).mean()
    
    if h_plus_error < current_error:
        w = w + h
        continue
        
    y_predict = (w - h) * x
    h_minus_error = np.abs(y - y_predict).mean()
    
    if h_minus_error < current_error:
        w = w - h
        continue

    break
    
error = current_error
print("{0} error = {1:.5f}, w = {2:.5f}".format(epoch, error, w))

62 error = 0.00014, w = 0.29970


### Case 3 - Gradient Descent

In [26]:
num_epoch = 50000
learning_rate = 0.1

w1 = np.random.uniform(low=0.0, high=1.0)
w2 = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_predict = w1 * x1 + w2 * x2 + b
    
    error = np.power(y_predict - y1, 2).mean()
    
    if error < 0.00001:
        break
        
    w1 = w1 - learning_rate * ((y_predict - y1) * x1).mean()
    w2 = w2 - learning_rate * ((y_predict - y1) * x2).mean()
    b = b - learning_rate * (y_predict - y1).mean()

print("------" * 10)
print("{0} error = {1:.5f}, w1 = {2:.5f}, w2 = {3:.5f}, b = {4:.5f}"\
      .format(epoch, error, w1, w2, b))

------------------------------------------------------------
730 error = 0.00001, w1 = 0.28951, w2 = 0.49531, b = 0.10792


In [14]:
from sklearn.datasets import load_boston

boston = load_boston()

In [15]:
X = boston["data"]

print(X.shape)
X[:1]

(506, 13)


array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
          0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
          6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
          2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
          4.98000000e+00]])

In [16]:
Y = boston["target"]

print(Y.shape)
Y[:10]

(506,)


array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,  18.9])

In [17]:
import pandas as pd

data = pd.DataFrame(X, columns = boston["feature_names"])
data["target"] = Y

print(data.shape)
data.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [6]:

'''
num_epoch = 10000000000000
learning_rate = 0.0001
Y = Y.reshape((506,1))
W = np.random.uniform(low=0.0, high=1.0, size=(13,1))
b = np.random.uniform(low=0.0, high=1.0, size=(506,1))
for epoch in range(num_epoch):
    y_predict = np.matmul(X, W) + b

    error = np.mean(np.abs(y_predict - Y))
    print(error)
    
    if error < 0.000000001:
        break
    #X_feature = (x - m) / (max - min)
    W = W - learning_rate * np.mean(np.matmul(np.transpose(X), y_predict - Y), axis=0)
    b = b - learning_rate * np.mean(y_predict - Y, axis=0)
print("W =", W, ", b =", b)
'''

#(X.T X)^ X.T y

'\nnum_epoch = 10000000000000\nlearning_rate = 0.0001\nY = Y.reshape((506,1))\nW = np.random.uniform(low=0.0, high=1.0, size=(13,1))\nb = np.random.uniform(low=0.0, high=1.0, size=(506,1))\nfor epoch in range(num_epoch):\n    y_predict = np.matmul(X, W) + b\n\n    error = np.mean(np.abs(y_predict - Y))\n    print(error)\n    \n    if error < 0.000000001:\n        break\n    #X_feature = (x - m) / (max - min)\n    W = W - learning_rate * np.mean(np.matmul(np.transpose(X), y_predict - Y), axis=0)\n    b = b - learning_rate * np.mean(y_predict - Y, axis=0)\nprint("W =", W, ", b =", b)\n'

In [73]:
a  = np.array([[1,2,3],[4,5,6]])

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.mean(a, axis=0)

array([ 2.5,  3.5,  4.5])

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
b = np.array([[1] for i in range(506)])

In [12]:
b.shape

(506, 1)

In [18]:
temp = np.c_[b,X]

In [19]:
temp.shape

(506, 14)

###  (X.T X)^ X.T y

In [26]:
theta = np.dot(np.dot(lin.inv(np.dot(temp.T,temp)),temp.T),Y)
theta.shape

(14,)

In [29]:
res = np.dot(temp, theta)

In [30]:
Y

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,

In [31]:
np.mean(np.abs(res - Y))

3.2729446379966332